# imagen base
FROM ubuntu
# metadatos
LABEL version="1.0" mainteiner="aperezrodriguez@danielcastelao.org"
# ejecuta el comando dentro de la imagen base
RUN apt update
RUN apt install -y iputils-ping 
#comando que va a ejecutar el contendor
CMD ["ping", "www.google.com"]